WITH Ultima_Cerca AS (
    SELECT 
        CERCA.CODCLIFOR AS 'CÓDIGO_DO_CLIENTE',
        CERCA.NOME AS 'CERCA', 
        CERCA_GRUPO.DESCRICAO AS 'GRUPO_DA_CERCA', 
        RVEI.NUMVEI AS 'PLACA', 
        RCH.DATA_ENTRADA, 
        RCH.DATA_SAIDA,
        ROW_NUMBER() OVER(PARTITION BY RVEI.NUMVEI ORDER BY RCH.DATA_ENTRADA DESC) AS rn
    FROM CERCA_HISTORICO AS RCH
    LEFT JOIN RODVEI AS RVEI ON RVEI.CODVEI = RCH.VEICULO
    LEFT JOIN CERCA ON CERCA.ID = RCH.CERCA_ID
    LEFT JOIN CERCA_GRUPO ON CERCA_GRUPO.ID = CERCA.GRUPO_ID
    WHERE CERCA_GRUPO.DESCRICAO IN ('EMBARCADOR', 'CLIENTE') 
        AND CERCA.NOME NOT IN ('REUTILIZAR')
),
Ultimo_KM_Vazio AS (
    SELECT 
        RVAZ.CODVAZ, 
        RVEI.NUMVEI AS 'PLACA', 
        RVEI1.NUMVEI AS 'CARRETA_1', 
        RVEI2.NUMVEI AS 'CARRETA_2',
        RVAZ.KMTSAI AS 'KM_DA_SAIDA', 
        RVAZ.KMTCHE AS 'KM_DA_CHEGADA', 
        RVAZ.DATSAI AS 'DATA_DA_SAIDA', 
        RVAZ.DATPRE AS 'PREVISAO_DE_CHEGADA', 
        ROW_NUMBER() OVER(PARTITION BY RVEI.NUMVEI ORDER BY RVAZ.DATSAI DESC) AS rn,
        RVAZ.DATINC AS 'DATA_DE_INCLUSAO', 
        RVAZ.DATBAI AS 'DATA_DA_BAIXA'
    FROM RODVAZ AS RVAZ
    LEFT JOIN RODVEI AS RVEI ON RVEI.CODVEI = RVAZ.CODVEI
    LEFT JOIN RODVEI AS RVEI1 ON RVEI1.CODVEI = RVAZ.PLACA2
    LEFT JOIN RODVEI AS RVEI2 ON RVEI2.CODVEI = RVAZ.PLACA3
    WHERE RVAZ.DATINC >= '2024-01-01'
),
CTE AS (
    SELECT 
        RCON.CODCON AS DOCUMENTO,
        RCON.CODFIL AS FILIAL, 
        RCON.DATINC AS DATA_INCLUSAO, 
        CASE 
            WHEN RCON.SITUAC = 'D' THEN 'CADASTRADA'
            WHEN RCON.SITUAC = 'E' THEN 'EMITIDO'
            WHEN RCON.SITUAC = 'B' THEN 'BAIXADO'
        END AS SITUACAO, 
        RCON.DATBAI AS DATA_BAIXA, 
        RVEI.NUMVEI AS PLACA, 
        RCLI1.NOMEAB AS REMETENTE,
        RCLI3.NOMEAB AS TERMINAL_COLETA,
        RCON.TERCOL AS CODIGO_COLETA,
        RCLI4.NOMEAB AS TERMINAL_ENTREGA,
        RCON.TERENT AS CODIGO_ENTREGA,
        RCLI1.CODCLIFOR AS CODIGO_REMETENTE,
        RCLI.NOMEAB AS DESTINATARIO, 
        RCLI.CODCLIFOR AS CODIGO_DESTINATARIO,
        RCLI2.NOMEAB AS PAGADOR
    FROM RODCON AS RCON
    LEFT JOIN RODVEI AS RVEI ON RVEI.CODVEI = RCON.PLACA 
    LEFT JOIN RODCLI AS RCLI ON RCLI.CODCLIFOR = RCON.CODDES
    LEFT JOIN RODCLI AS RCLI1 ON RCLI1.CODCLIFOR = RCON.CODREM
    LEFT JOIN RODCLI AS RCLI2 ON RCLI2.CODCLIFOR = RCON.CODPAG
    LEFT JOIN RODCLI AS RCLI3 ON RCLI3.CODCLIFOR = RCON.TERCOL
    LEFT JOIN RODCLI AS RCLI4 ON RCLI4.CODCLIFOR = RCON.TERENT
    WHERE RCON.DATINC >= '2024-07-01' 
      AND RCON.SITUAC IN ('E', 'D', 'B') 
      AND RVEI.CODFRO = '4' 
      AND RVEI.CODCMO IN ('1', '29', '53')
      AND RCON.TIPCON NOT IN ('S', 'C', 'U', 'B', 'V')
	  AND RVEI.OPEGES NOT IN ('GEISA.KARLA')
),
OST AS (
    SELECT 
        RORD.CODIGO AS DOCUMENTO, 
        RORD.SERORD AS ORDEM,
        RORD.TIPDOC AS TIPO_DOCUMENTO, 
        RORD.CODFIL AS FILIAL,
        RORD.DATINC AS DATA_INCLUSAO, 
        RORD.DATBAI AS DATA_BAIXA, 
        RVEI.NUMVEI AS PLACA, 
        RCLI.NOMEAB AS REMETENTE,
        RCLI.CODCLIFOR AS CODIGO_REMETENTE, 
        RCLI1.NOMEAB AS DESTINATARIO, 
        RCLI1.CODCLIFOR AS CODIGO_DESTINATARIO,
        RCLI3.NOMEAB AS TERMINAL_COLETA,
        RORD.TERCOL AS CODIGO_COLETA, 
        RCLI4.NOMEAB AS TERMINAL_ENTREGA, 
        RORD.TERENT AS CODIGO_ENTREGA
    FROM RODORD AS RORD
    LEFT JOIN RODCLI AS RCLI ON RCLI.CODCLIFOR = RORD.CODREM
    LEFT JOIN RODCLI AS RCLI1 ON RCLI1.CODCLIFOR = RORD.CODDES
    LEFT JOIN RODCLI AS RCLI3 ON RCLI3.CODCLIFOR = RORD.TERCOL
    LEFT JOIN RODCLI AS RCLI4 ON RCLI4.CODCLIFOR = RORD.TERENT
    LEFT JOIN RODVEI AS RVEI ON RVEI.CODVEI = RORD.PLACA
    WHERE RORD.DATINC >= '2024-07-01' 
      AND RORD.SITUAC IN ('D', 'E', 'B')
      AND RVEI.CODFRO = '4' 
      AND RVEI.CODCMO IN ('1', '29', '53')
	  AND RVEI.OPEGES NOT IN ('GEISA.KARLA')
),
Combined AS (
    SELECT 
        DOCUMENTO,
		FILIAL,
        PLACA, 
        DATA_INCLUSAO, 
        ORIGEM,
        REMETENTE,
        CODIGO_REMETENTE,
        TERMINAL_COLETA,
        CODIGO_COLETA,
        DESTINATARIO,
        CODIGO_DESTINATARIO,
        TERMINAL_ENTREGA,
        CODIGO_ENTREGA,
        ROW_NUMBER() OVER (PARTITION BY PLACA ORDER BY DATA_INCLUSAO DESC) AS rn
    FROM (
        SELECT DOCUMENTO, FILIAL, PLACA, DATA_INCLUSAO, 'CTE' AS ORIGEM, 
               REMETENTE, CODIGO_REMETENTE, TERMINAL_COLETA, CODIGO_COLETA, 
               DESTINATARIO, CODIGO_DESTINATARIO, TERMINAL_ENTREGA, CODIGO_ENTREGA
        FROM CTE
        UNION
        SELECT DOCUMENTO, FILIAL, PLACA, DATA_INCLUSAO, 'OST' AS ORIGEM, 
               REMETENTE, CODIGO_REMETENTE, TERMINAL_COLETA, CODIGO_COLETA, 
               DESTINATARIO, CODIGO_DESTINATARIO, TERMINAL_ENTREGA, CODIGO_ENTREGA
        FROM OST
    ) AS CombinedData
),
Estados_Veiculo AS (
    SELECT 
        d.PLACA,
        d.DOCUMENTO,
        d.FILIAL,
		d.ORIGEM,
        d.DATA_INCLUSAO,
        d.REMETENTE,
        d.CODIGO_REMETENTE,
        d.DESTINATARIO,
        d.CODIGO_DESTINATARIO,
        c.CÓDIGO_DO_CLIENTE AS ULTIMA_CERCA_CLIENTE,
        UPPER (c.CERCA) AS NOME_ULTIMA_CERCA,
        c.DATA_ENTRADA AS DATA_ENTRADA_ULTIMA_CERCA,
        c.DATA_SAIDA AS DATA_SAIDA_ULTIMA_CERCA,
        km.KM_DA_SAIDA,
        km.KM_DA_CHEGADA,
        km.DATA_DE_INCLUSAO AS DATA_INCLUSAO_VAZIO,
        CASE
            WHEN c.CÓDIGO_DO_CLIENTE = d.CODIGO_REMETENTE 
                 AND c.DATA_SAIDA IS NULL THEN 'T2 - Carregando'
            WHEN c.CÓDIGO_DO_CLIENTE = d.CODIGO_REMETENTE  
                 AND c.DATA_SAIDA IS NOT NULL THEN 'T3 - Deslocando para Descarregar'
            WHEN c.CÓDIGO_DO_CLIENTE = d.CODIGO_DESTINATARIO 
                 AND c.DATA_SAIDA IS NULL THEN 'T4 - Descarregando'
            WHEN c.CÓDIGO_DO_CLIENTE = d.CODIGO_DESTINATARIO 
                 AND c.DATA_SAIDA IS NOT NULL THEN 'T1 - Deslocando para Carregar'
            ELSE 'T1 - Deslocando para Carregar'
        END AS ESTADO_VEICULO
    FROM Ultima_Cerca AS c
    INNER JOIN Combined AS d ON c.PLACA = d.PLACA
    LEFT JOIN Ultimo_KM_Vazio AS km ON c.PLACA = km.PLACA AND km.rn = 1
    WHERE c.rn = 1 AND d.rn = 1 AND d.DESTINATARIO IN ('CETREL - VIA ATLANTICA')
)

SELECT *
FROM Estados_Veiculo;

